#!/bin/bash

echo "======================================"
echo "  个人指标管理系统 - 手动安装指南"
echo "======================================"
echo ""

echo "⚠️  检测到你可能遇到 npm 权限问题。"
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1️⃣  修复 npm 权限（需要输入密码）："
echo "   sudo chown -R \$(whoami) ~/.npm"
echo ""
echo "2️⃣  安装根目录依赖："
echo "   npm install"
echo ""
echo "3️⃣  安装服务端依赖："
echo "   cd server && npm install && cd .."
echo ""
echo "4️⃣  安装客户端依赖（使用 legacy-peer-deps）："
echo "   cd client && npm install --legacy-peer-deps && cd .."
echo ""
echo "5️⃣  配置服务端环境变量："
echo "   cd server"
echo "   # 如果没有 .env 文件，复制示例文件"
echo "   cp .env.example .env  # 然后编辑这个文件"
echo "   cd .."
echo ""
echo "6️⃣  启动服务器并注册账号："
echo "   # 在一个终端启动服务器"
echo "   cd server && npm start"
echo ""
echo "   # 在另一个终端注册管理员"
echo "   curl -X POST http://localhost:3001/api/auth/register \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"username\":\"admin\",\"password\":\"admin123\"}'"
echo ""
echo "7️⃣  启动完整应用："
echo "   npm run dev"
echo ""
echo "======================================"
echo "更多详细说明请查看 INSTALL.md 文件"
echo "======================================"

